services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: